[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer"
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/fotos/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
